/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicWireGithubRouteImport } from './routes/api/public/wire-github'
import { Route as ApiPublicRunEventsRouteImport } from './routes/api/public/run-events'

const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWireGithubRoute = ApiPublicWireGithubRouteImport.update({
  id: '/api/public/wire-github',
  path: '/api/public/wire-github',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRunEventsRoute = ApiPublicRunEventsRouteImport.update({
  id: '/api/public/run-events',
  path: '/api/public/run-events',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/api/public/run-events': typeof ApiPublicRunEventsRoute
  '/api/public/wire-github': typeof ApiPublicWireGithubRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/api/public/run-events': typeof ApiPublicRunEventsRoute
  '/api/public/wire-github': typeof ApiPublicWireGithubRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/api/public/run-events': typeof ApiPublicRunEventsRoute
  '/api/public/wire-github': typeof ApiPublicWireGithubRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/chat'
    | '/api/public/run-events'
    | '/api/public/wire-github'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/chat'
    | '/api/public/run-events'
    | '/api/public/wire-github'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/chat'
    | '/api/public/run-events'
    | '/api/public/wire-github'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ChatRoute: typeof ChatRoute
  ApiPublicRunEventsRoute: typeof ApiPublicRunEventsRoute
  ApiPublicWireGithubRoute: typeof ApiPublicWireGithubRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/wire-github': {
      id: '/api/public/wire-github'
      path: '/api/public/wire-github'
      fullPath: '/api/public/wire-github'
      preLoaderRoute: typeof ApiPublicWireGithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/run-events': {
      id: '/api/public/run-events'
      path: '/api/public/run-events'
      fullPath: '/api/public/run-events'
      preLoaderRoute: typeof ApiPublicRunEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ChatRoute: ChatRoute,
  ApiPublicRunEventsRoute: ApiPublicRunEventsRoute,
  ApiPublicWireGithubRoute: ApiPublicWireGithubRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
