/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScannerRouteImport } from './routes/scanner'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as OpportunitiesRouteImport } from './routes/opportunities'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicWireGithubRouteImport } from './routes/api/public/wire-github'
import { Route as ApiPublicRunEventsRouteImport } from './routes/api/public/run-events'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScannerRoute = ScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesRoute = OpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWireGithubRoute = ApiPublicWireGithubRouteImport.update({
  id: '/api/public/wire-github',
  path: '/api/public/wire-github',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRunEventsRoute = ApiPublicRunEventsRouteImport.update({
  id: '/api/public/run-events',
  path: '/api/public/run-events',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/leads': typeof LeadsRoute
  '/opportunities': typeof OpportunitiesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/scanner': typeof ScannerRoute
  '/settings': typeof SettingsRoute
  '/api/public/run-events': typeof ApiPublicRunEventsRoute
  '/api/public/wire-github': typeof ApiPublicWireGithubRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/leads': typeof LeadsRoute
  '/opportunities': typeof OpportunitiesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/scanner': typeof ScannerRoute
  '/settings': typeof SettingsRoute
  '/api/public/run-events': typeof ApiPublicRunEventsRoute
  '/api/public/wire-github': typeof ApiPublicWireGithubRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/leads': typeof LeadsRoute
  '/opportunities': typeof OpportunitiesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/scanner': typeof ScannerRoute
  '/settings': typeof SettingsRoute
  '/api/public/run-events': typeof ApiPublicRunEventsRoute
  '/api/public/wire-github': typeof ApiPublicWireGithubRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/leads'
    | '/opportunities'
    | '/reset-password'
    | '/scanner'
    | '/settings'
    | '/api/public/run-events'
    | '/api/public/wire-github'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/leads'
    | '/opportunities'
    | '/reset-password'
    | '/scanner'
    | '/settings'
    | '/api/public/run-events'
    | '/api/public/wire-github'
  id:
    | '__root__'
    | '/'
    | '/leads'
    | '/opportunities'
    | '/reset-password'
    | '/scanner'
    | '/settings'
    | '/api/public/run-events'
    | '/api/public/wire-github'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LeadsRoute: typeof LeadsRoute
  OpportunitiesRoute: typeof OpportunitiesRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ScannerRoute: typeof ScannerRoute
  SettingsRoute: typeof SettingsRoute
  ApiPublicRunEventsRoute: typeof ApiPublicRunEventsRoute
  ApiPublicWireGithubRoute: typeof ApiPublicWireGithubRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scanner': {
      id: '/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof ScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities': {
      id: '/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof OpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/wire-github': {
      id: '/api/public/wire-github'
      path: '/api/public/wire-github'
      fullPath: '/api/public/wire-github'
      preLoaderRoute: typeof ApiPublicWireGithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/run-events': {
      id: '/api/public/run-events'
      path: '/api/public/run-events'
      fullPath: '/api/public/run-events'
      preLoaderRoute: typeof ApiPublicRunEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LeadsRoute: LeadsRoute,
  OpportunitiesRoute: OpportunitiesRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ScannerRoute: ScannerRoute,
  SettingsRoute: SettingsRoute,
  ApiPublicRunEventsRoute: ApiPublicRunEventsRoute,
  ApiPublicWireGithubRoute: ApiPublicWireGithubRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
