/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicWireGithubRouteImport } from './routes/api/public/wire-github'
import { Route as ApiPublicRunEventsRouteImport } from './routes/api/public/run-events'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWireGithubRoute = ApiPublicWireGithubRouteImport.update({
  id: '/api/public/wire-github',
  path: '/api/public/wire-github',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRunEventsRoute = ApiPublicRunEventsRouteImport.update({
  id: '/api/public/run-events',
  path: '/api/public/run-events',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/api/public/run-events': typeof ApiPublicRunEventsRoute
  '/api/public/wire-github': typeof ApiPublicWireGithubRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/api/public/run-events': typeof ApiPublicRunEventsRoute
  '/api/public/wire-github': typeof ApiPublicWireGithubRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/api/public/run-events': typeof ApiPublicRunEventsRoute
  '/api/public/wire-github': typeof ApiPublicWireGithubRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/reset-password'
    | '/settings'
    | '/api/public/run-events'
    | '/api/public/wire-github'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/reset-password'
    | '/settings'
    | '/api/public/run-events'
    | '/api/public/wire-github'
  id:
    | '__root__'
    | '/'
    | '/reset-password'
    | '/settings'
    | '/api/public/run-events'
    | '/api/public/wire-github'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  ApiPublicRunEventsRoute: typeof ApiPublicRunEventsRoute
  ApiPublicWireGithubRoute: typeof ApiPublicWireGithubRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/wire-github': {
      id: '/api/public/wire-github'
      path: '/api/public/wire-github'
      fullPath: '/api/public/wire-github'
      preLoaderRoute: typeof ApiPublicWireGithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/run-events': {
      id: '/api/public/run-events'
      path: '/api/public/run-events'
      fullPath: '/api/public/run-events'
      preLoaderRoute: typeof ApiPublicRunEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  ApiPublicRunEventsRoute: ApiPublicRunEventsRoute,
  ApiPublicWireGithubRoute: ApiPublicWireGithubRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
